### ISSUE TITLE
comment required for __toString

### ISSUE THREAD

**Issue by trylika** [ongr-io/ongr-strict-standard#109]
Standard requires comment on __toString function, if comment for __construct is not required, neither should it be in here. Applies for 2.* version.

```
    /**
     * @return string
     */
    public function __toString()
    {
        return 'aa';
    }
```

**Comment by tautrimas** [comment]
In ongr-strict-stanard v1, required comments for such magic methods were removed. Must migrate these exceptions to v2.

Alternatively simply write:

```php

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->name;
    }
```
