### ISSUE TITLE
Checker throws PHP notices on empty function @return comments.

### ISSUE THREAD

**Issue by kewlar** [ongr-io/ongr-strict-standard#136]
Let's say we have a `@return int ` in a function's docblock.  Here, `$token['content'] === 'int '`. The result:

```
PHP Notice: Uninitialized string offset: 0 in .../ongr/ongr-strict-standard/Ongr/Sniffs/Commenting/FunctionCommentSniff.php on line 313
```

The sniffer correctly reports "Whitespace found at end of line", but it also incorrectly adds "Return comment must start with a capital letter" and "Return comment must end with a full stop". There should not be further errors about a return comment, because there is no return comment.

The bug is both in 2.x and in master branches (line 332 on master branch).

**Comment by tautrimas** [comment]
Hi (:

Do you have an example with more context?

**Comment by kewlar** [comment]
Sure thing (:

```php
    /**
     * Get company
     *
     * @return \Pim\UserBundle\Entity\Company 
     */
    public function getCompany()
    {
        return $this->company;
    }
```

The Doctrine entity code here was probably generated by an IDE or a `doctrine:generate:entities` command, and it -- stupidly -- left a space symbol at the end of the `@return` line (not sure if the comment will preserve the whitespace).

The code sniffer throws up on that:
<img width="548" alt="ongr-sniffer-error" src="https://cloud.githubusercontent.com/assets/1241866/9604290/598e85f0-50bf-11e5-9e14-c60c2df15c7d.png">

If you don't mind, I've got a test, and a fix. Pull request incoming in 3... 2... 1...
