### ISSUE TITLE
Comments on new line

### ISSUE THREAD

**Issue by trylika** [ongr-io/ongr-strict-standard#47]
It's possible to write variable comment like this:

```
/**
 * @var int
 * Represents document count for option.
*/
```
Is this supposed to be?

**Comment by tautrimas** [comment]
Such style is cannot be accepted, such text is only valid if indented (not like above) as per PSR-5.

All in all, we should not implement this checking and wait for proper PSR-5 PHPCS implementation.

**Comment by trylika** [comment]
When PSR-5 will be implemented? if it's 1year to wait, maybe we should do it?

**Comment by saimaz** [comment]
Sooner or later PSR-5 will be released. Why don't we check how its required in PSR-5 from now?
