### ISSUE TITLE
Investigate concatenation (.) operator usage

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/ongr-strict-standard#49]
Investigate, if more often than not spaces are left or removed around `.` operator in most popular frameworks.

**Comment by saimaz** [comment]
+1 for `.` with spaces around

Well, maybe we should follow other operators convention because now it's the same like 
```php
if ($a+$b) {
```

So why to use `$a.'_'` when with spaces it will look much cleaner?

```php
$a.'_';
$a . '_';
```

**Comment by tautrimas** [comment]
Here are the results:

Framework | Is space
--- | ---
CakePHP | true
Laravel | false
Phalcon | true
Silex | false
Symfony | false
YII | true
Zend 2 | true

Statistics are approximately the same, therefore we leave spaces due to argument above.
