### ISSUE TITLE
Make a proper manual for Windows, for people without composer and even without Php (LAMP/WAMP) installation on PC

### ISSUE THREAD

**Issue by KestutisIT** [ongr-io/ongr-strict-standard#55]
Below are my notes about how to make this tool more useful.

## Setup for Windows 8.1:

**System requirements:**
1. Windows 8.1
1. Zend Server Free Edition
2. Php Storm 8.01

**Installation steps:**
1. (optional for separate PHP install) download http://windows.php.net/download/#php-5.4
2. download http://pear.php.net/go-pear.phar
3. Start -> RUN -> cmd.
4. (optional for separate PHP install) cd c:\php
5. Go to Php.exe directory in Zend Server installation folder:
cd C:\Program Files (x86)\Zend\ZendServer\bin\
5. Install PEAR:
php go-pear.phar
6. Install Php Code Sniffer:
pear install PHP_CodeSniffer
7. use [download in zip] from https://github.com/ongr-io/ongr-strict-standard
*Or you [clone it to desktop] via "Github for Windows" sofware, which may or may not start after "[clone it to desktop]" button click 
8. Extact content to (or similar folder):
C:\Program Files (x86)\Zend\Apache2\htdocs\GitHub\ProgrammingAssignments\NFQ-Challenge\ONGR
Make sure travis.sh in the ONGR folder.
9. Go to PhpStorm IDE -> Settings -> Languages & Frameworks -> Code Sniffer
10. Click [...] (browse) next to "Php Code Sniffer (phpcs) path"
11. Locate C:\Program Files (x86)\Zend\ZendServer\bin\PEAR\PHPCS\phpcs.exe file

---
**Some sources to read:**
http://kogentadono.com/2012/10/08/installing-php-5-4-and-php-codesniffer-on-windows/
http://www.jetbrains.com/phpstorm/help/using-php-code-sniffer-tool.html

---
**Things to consider:**
1. Instead of doing runtime validation, it might be enough for Windows users or other to make this as a separate PhpStorm plugin, installable from Menu->Settings->Plugins->[Browse Repositories...]
2. And just having highlighting in IDE, without having runtime code validation.
3. Zend Server Free Edition is one of few really working WAMP stacks in Windows, its easy-to-use.
4. When we come to changing configuration WAMP setup, things gets complicated.
5. It may be easier to restart my computer to boot Ubuntu Linux, and this would fit advice of Pieter Hintjens  ( @hintjens ), founder of ZeroMQ:
"Kestutis, it is not about you can prove it that it can work on Windows or not, it's about does your computer helps you or not. With this task I see that your computer doesn't help you".
And I totally agree, that I doesn't make any sense to prove it, but the thing is that because there were no Windows manual I dropped this idea 'until smarter times', 'until next reboot' or 'until I finally finish my configuration in Linux'. In Linux I face other problems like that there is no drivers for my USB 3.0 to 2xHDMI splitter, and I cant run two screens with closed laptop, or I have not fully configured PhpStorm install. So these 'small' excuses, until somebody forces me and help me with that setup makes me 'leave it for later'. And if your goal is to make this think popular, you have to think how to attract these 'leave it for later' thinking people. Otherwise it's just solving a problem for some small group of people, but does not have impact to the majority developers. 

---
The End

**Comment by tautrimas** [comment]
Hello @KestutisIT,

Officially we support installation methods that are provided with the documentation. Thank you for the valuable details you have provided. They will be located in this ticket for the alternative installation method seekers in the future.

As for the native PHPStorm support: we may consider this approach for the roadmap, however, CodeSniffer is _de facto_ most popular code style validator for PHP and it recently got to improved 2.x major version which we are looking forward to support. To add more, binding to specific IDE will hurt users that are using other code editing products that already have PHPCS integration.

Thank you!
