### ISSUE TITLE
method's return comment is not validated 

### ISSUE THREAD

**Issue by trylika** [ongr-io/ongr-strict-standard#87]
Applies to v1.0.0.
There is absolutely no difference for phpcs among these lines:

```
    /**
     * @return \Symfony\Component\Form\Form the form
     * @return \Symfony\Component\Form\Form The form
     * @return \Symfony\Component\Form\Form the form.
     */
```

**Comment by saimaz** [comment]
@chyzas, @tautrimas  what do you think about this?

**Comment by tautrimas** [comment]
IMO, these comments and similar others, like `@throws` should be validated with the same logic as `@param`. I don't know, but that should be relatively easy to enable.

**Comment by trylika** [comment]
i would generalize such rule: everywhere, where comment could be written, it should be validated against our default logic - must start with capital letter and end with dot or other symbol which defines end of a sentence.

**Comment by tautrimas** [comment]
> or other symbol which defines end of a sentence.

Currently, as of Squiz standard, other punctuation is allowed only in inline comments. Not PHPDoc comments, where it must end with a dot.
